export const REQUEST_WORK_ORDERS = 'REQUEST_WORK_ORDERS';
export const TOGGLE_SWITCH = 'TOGGLE_SWITCH';
export const RECIEVE_WORK_ORDERS = 'RECIEVE_WORK_ORDERS';
export const SEARCH_INPUT = 'SEARCH_INPUT'